package studio.cluvex.aether.core

import android.content.Context
import android.os.SystemClock
import kotlinx.coroutines.delay
import studio.cluvex.aether.model.ConnectionProfile
import java.io.File

/**
 * The torrc this app runs tor with.
 *
 * Kept as a PURE function of its inputs so it can be unit-tested: a torrc is
 * the whole configuration surface of the Tor hop, and "did we write the
 * upstream proxy line" is exactly the kind of thing that must not need a device
 * to verify. Every option below is either load-bearing or explained.
 */
internal object Torrc {

    fun build(
        dataDir: String,
        socksPort: Int,
        dnsPort: Int,
        /** Local SOCKS5 the whole Tor client dials through, or null for direct. */
        upstreamPort: Int?,
        /** Two-letter exit country, or null. Ignored without a geoip database. */
        exitCountry: String?,
        strictNodes: Boolean,
        /** tor's geoip / geoip6 files, when they were bundled with the build. */
        geoipFile: String?,
        geoip6File: String?,
    ): String = buildString {
        appendLine("# Generated by Aether. Do not edit: rewritten on every connect.")
        appendLine("DataDirectory $dataDir")
        // Never group-readable: tor refuses to start on a data directory it
        // considers too permissive, and this one lives in app-private storage.
        appendLine("DataDirectoryGroupReadable 0")
        appendLine("AvoidDiskWrites 1")
        // This is a client. Never a relay, never a bridge, whatever else is set.
        appendLine("ClientOnly 1")
        appendLine("SocksPort ${TunnelConfig.SOCKS_HOST}:$socksPort IPv6Traffic PreferIPv6")
        // The DNS answer path for the whole device: see SocksFront. Without
        // this, TCP works and nothing resolves.
        appendLine("DNSPort ${TunnelConfig.SOCKS_HOST}:$dnsPort")
        // Makes .onion names resolvable through that DNSPort, so hidden services
        // work from any app on the device and not only from a Tor-aware one.
        appendLine("AutomapHostsOnResolve 1")
        appendLine("AutomapHostsSuffixes .onion,.exit")
        // No control port: nothing in this app speaks the control protocol, and
        // an open control port on loopback is a local privilege boundary we do
        // not need to defend.
        appendLine("ControlPort 0")
        appendLine("CookieAuthentication 0")
        // Bootstrap progress is parsed out of these lines; SafeLogging keeps
        // addresses out of them.
        appendLine("Log notice stdout")
        appendLine("SafeLogging 1")

        // CHAINING: one line is what "Tor over Psiphon over Aether" is. It
        // covers every OR and directory connection tor makes, so the ISP sees
        // only the previous hop's traffic.
        if (upstreamPort != null) {
            appendLine("Socks5Proxy ${TunnelConfig.SOCKS_HOST}:$upstreamPort")
        }

        if (geoipFile != null) appendLine("GeoIPFile $geoipFile")
        if (geoip6File != null) appendLine("GeoIPv6File $geoip6File")

        // Country selection needs the geoip database to mean anything at all;
        // with no database tor logs a warning and silently ignores the request,
        // which looks like the setting is broken.
        val country = exitCountry?.trim()?.lowercase()?.takeIf { it.matches(COUNTRY) }
        if (country != null && geoipFile != null) {
            appendLine("ExitNodes {$country}")
            if (strictNodes) appendLine("StrictNodes 1")
        }
    }

    private val COUNTRY = Regex("^[a-z]{2}$")
}

/**
 * tor, run as a child process.
 *
 * The binary is the Tor Project / Guardian Project Android build (`libtor.so`),
 * the same one Orbot ships, installed into jniLibs by
 * `scripts/build-natives.sh`. It is a normal executable under a `.so` name, so
 * it runs through [NativeChild] like every other core here.
 *
 * Readiness is tor's OWN bootstrap report. "The SOCKS port is open" is useless
 * for tor: it binds the port immediately and then spends anywhere from a few
 * seconds to a couple of minutes building a circuit, refusing every CONNECT in
 * the meantime. `Bootstrapped 100%` is the only thing that means ready, and the
 * intermediate percentages are worth showing the user, because a Tor bootstrap
 * that has reached 80% is progress and one that sits at 5% is a blocked network.
 */
class TorCore(
    private val context: Context,
    filesDir: File,
) {
    private val dataDir = File(filesDir, "tor").apply { mkdirs() }

    private val child = NativeChild(
        tag = TAG,
        binaryName = BINARY,
        nativeLibDir = context.applicationInfo.nativeLibraryDir,
        workingDir = dataDir,
    )

    /** Last bootstrap percentage tor reported. Written on the log-drain thread. */
    @Volatile
    var bootstrapPercent = 0
        private set

    val isAvailable: Boolean get() = child.isAvailable
    val isAlive: Boolean get() = child.isAlive()
    val isReady: Boolean get() = bootstrapPercent >= 100

    /**
     * @param upstreamPort local SOCKS5 port tor must make all its connections
     *   through (the previous hop), or null to reach the Tor network directly.
     */
    fun start(profile: ConnectionProfile, upstreamPort: Int?) {
        bootstrapPercent = 0
        val geoip = installGeoip("geoip")
        val geoip6 = installGeoip("geoip6")
        if (geoip == null && profile.torExitCountry.isNotBlank()) {
            DiagnosticsLog.w(
                TAG,
                "No geoip database in this build - the Tor exit country will be ignored.",
            )
        }
        val torrc = Torrc.build(
            dataDir = dataDir.absolutePath,
            socksPort = TunnelConfig.TOR_SOCKS_PORT,
            dnsPort = TunnelConfig.TOR_DNS_PORT,
            upstreamPort = upstreamPort,
            exitCountry = profile.torExitCountry,
            strictNodes = profile.torStrictNodes,
            geoipFile = geoip,
            geoip6File = geoip6,
        )
        val torrcFile = File(dataDir, "torrc")
        torrcFile.writeText(torrc)
        DiagnosticsLog.i(TAG, "torrc written:\n$torrc")
        child.start(args = listOf("-f", torrcFile.absolutePath), onLine = ::onLine)
    }

    fun stop() = child.stop()

    suspend fun awaitExit(timeoutMs: Long): Boolean = child.awaitExit(timeoutMs)

    /** Waits for `Bootstrapped 100%`; false on timeout or if tor dies. */
    suspend fun awaitReady(timeoutMs: Long): Boolean {
        val deadline = SystemClock.elapsedRealtime() + timeoutMs
        var lastReported = -1
        while (SystemClock.elapsedRealtime() < deadline) {
            if (isReady) {
                DiagnosticsLog.i(TAG, "Tor bootstrapped - circuit is ready.")
                return true
            }
            if (!isAlive) {
                DiagnosticsLog.e(TAG, "Tor exited during bootstrap (${bootstrapPercent}%).")
                return false
            }
            if (bootstrapPercent != lastReported) {
                lastReported = bootstrapPercent
                ChainRuntime.update(
                    studio.cluvex.aether.model.Hop.TOR,
                    ChainRuntime.HopState.STARTING,
                    "$bootstrapPercent%",
                )
            }
            delay(POLL_MS)
        }
        DiagnosticsLog.e(
            TAG,
            "Tor stalled at ${bootstrapPercent}% after ${timeoutMs / 1000}s - the network is " +
                "blocking the Tor network itself. Try Tor over Aether or Tor over Psiphon.",
        )
        return false
    }

    // ------------------------------------------------------------- internals

    /**
     * Copies tor's geoip database out of assets, once per install-version.
     *
     * tor needs a real file path, and an asset is not one. Returns null when the
     * build does not bundle the database, which is a supported state: only exit
     * country selection depends on it.
     */
    private fun installGeoip(name: String): String? {
        val target = File(dataDir, name)
        if (target.length() > 1024L) return target.absolutePath
        return runCatching {
            context.assets.open("$ASSET_DIR/$name").use { input ->
                target.outputStream().use { input.copyTo(it) }
            }
            target.absolutePath
        }.getOrNull()
    }

    private fun onLine(line: String) {
        val match = BOOTSTRAP.find(line) ?: return
        val percent = match.groupValues[1].toIntOrNull() ?: return
        if (percent > bootstrapPercent) bootstrapPercent = percent
    }

    companion object {
        const val TAG = "tor"

        /** The Tor Project's Android build, installed by build-natives.sh. */
        const val BINARY = "libtor.so"

        /** assets/tor/{geoip,geoip6}, fetched at build time. */
        const val ASSET_DIR = "tor"

        private const val POLL_MS = 500L

        /** "Bootstrapped 45% (requesting_descriptors): ..." */
        private val BOOTSTRAP = Regex("Bootstrapped (\\d{1,3})%")
    }
}
